#!/usr/bin/env bash
# Regenerate plugins.lock from the latest GitHub releases.
#
# plugins.lock is the single source of truth for which jars go into the images:
# the Dockerfile's fetch stage reads it and verifies every download against the
# recorded checksum. Nothing else records a version, so an ARG and a hash can
# never drift apart.
#
# Usage: hack/update-plugins.sh [--check]
#   --check  exit 1 if the lock is out of date, changing nothing (for CI)

set -euo pipefail

cd "$(dirname "$0")/.."

# scope  name        repo
#
# scope decides where the jar lands. BentoBox itself is a Paper plugin and goes
# in plugins/; its addons go in plugins/BentoBox/addons/ and will NOT load from
# plugins/ (Paper tries them as plugins and they die on NoClassDefFoundError:
# Pladdon). "common" addons ship in both images, the others are per-image.
PLUGINS=(
  "core      BentoBox    BentoBoxWorld/BentoBox"
  "common    Challenges  BentoBoxWorld/Challenges"
  "common    Border      BentoBoxWorld/Border"
  "common    Level       BentoBoxWorld/Level"
  "oneblock  AOneBlock   BentoBoxWorld/AOneBlock"
  "skyblock  BSkyBlock   BentoBoxWorld/BSkyBlock"
)

check_only=false
[[ "${1:-}" == "--check" ]] && check_only=true

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

lock="$tmp/plugins.lock"
{
  echo "# Generated by hack/update-plugins.sh -- do not edit by hand."
  echo "# scope name version filename sha256 url"
} >"$lock"

for entry in "${PLUGINS[@]}"; do
  read -r scope name repo <<<"$entry"

  release=$(gh api "repos/$repo/releases/latest")
  version=$(jq -r '.tag_name' <<<"$release")

  # Every BentoBox project ships exactly one jar asset per release. Select it
  # explicitly rather than assuming assets[0], and fail loudly if that stops
  # being true rather than silently baking the wrong file.
  mapfile -t jars < <(jq -r '.assets[] | select(.name | endswith(".jar")) | .name' <<<"$release")
  if [[ ${#jars[@]} -ne 1 ]]; then
    echo "error: $repo $version has ${#jars[@]} jar assets, expected 1: ${jars[*]-none}" >&2
    exit 1
  fi
  file="${jars[0]}"
  url="https://github.com/$repo/releases/download/$version/$file"

  echo "fetching $name $version" >&2
  curl -fsSL --retry 3 -o "$tmp/$file" "$url"
  # sha256sum on Linux/CI, shasum on macOS.
  if command -v sha256sum >/dev/null 2>&1; then
    sha=$(sha256sum "$tmp/$file" | cut -d' ' -f1)
  else
    sha=$(shasum -a 256 "$tmp/$file" | cut -d' ' -f1)
  fi

  printf '%s %s %s %s %s %s\n' "$scope" "$name" "$version" "$file" "$sha" "$url" >>"$lock"
done

if $check_only; then
  if diff -q plugins.lock "$lock" >/dev/null 2>&1; then
    echo "plugins.lock is up to date"
    exit 0
  fi
  echo "plugins.lock is out of date:" >&2
  diff -u plugins.lock "$lock" >&2 || true
  exit 1
fi

cp "$lock" plugins.lock
echo "wrote plugins.lock" >&2
